sudo: false

language: python
python:
  - '3.3'
  - '3.4'
  - '3.5'
  - '3.6'
  - '3.7-dev'
  - pypy3

install:
  - pip install -U pip setuptools
  - pip install -U -r requirements.test.txt
  - pip install -U tox
  - pip install -U -e .

script:
  - py.test -vv inheritly --doctest-modules
            --cov=inheritly --cov-fail-under=100

  - py.test -vv test --cov=inheritly --cov=test --cov-fail-under=100

  - tox -vre py$(perl -pe "s/(^py|\.|-dev$)//g" <<< $TRAVIS_PYTHON_VERSION)
